### ISSUE TITLE
Does not wake up with pin 31 nor unused pin 28 on my system.

### ISSUE THREAD

**Issue by kursatu** [OpenHAK/lazarus#1]
Couldn't get it to work with the default pin 31, nor with an unused pin 28 on my system.
Does it really work with Simblee? Is it tested
It did work with RFDuino, I recall tryin it out.

**Comment by lpercifield** [comment]
I've implemented this library in the OpenHAK firmware that is currently under development. See:https://github.com/OpenHAK/OHAK_firmware/blob/master/SFE_HeartRate_ble_sleep/SFE_HeartRate_ble_sleep.ino#L270
This allows the Simblee to be woken when BLE data is transferred. The loop then checks to see if the wakeup has been called and clears the flag as needed.

Apologies for the slow response. Closing for now
